### ISSUE TITLE
fails to separate similar tablenames from mysql

### ISSUE THREAD

**Issue by zesoup** [dimitri/pgloader#320]
Howdy!

It seems to me that `mysql-schema.lisp:210` doesnt force case-sensitivity, regardless of quote identifiers. This applies to default settings of a current debian-jessie mysql. I'm not sure if forcing to a case-sensitive collation is the best idea though.

==MySQL==
```
Create Table A(id int);
Create Table a(id int);
```

==PGLoader==
```
QUERY: CREATE TABLE a
(
  id                     bigint,
  id                     bigint
);
```

**Comment by dimitri** [comment]
Trying to reproduce here but my version of MySQL won't let me...

```
Create Table `a`(id int);
ERROR 1050 (42S01): Table 'a' already exists
```

**Comment by dimitri** [comment]
Please retry with current code, I think it's been fixed with the refactoring of the schema introspection...

**Comment by dimitri** [comment]
Should be fixed, closing. Please re-open if you still have the issue.

**Comment by zesoup** [comment]
Reopening, as i still see the issue upstream. Pullrequest with enforced casesensitivity exists. I'm not entirely convinced that this whole casesensitivity issue is fixed, but it seems like this one is.

used options, as i havent provided this before:

load database
     from      mysql://name@host/database  
     into postgresql:///mysqlclone
 
 WITH create tables, no truncate, quote identifiers, reset no sequences;

**Comment by dimitri** [comment]
Meanwhile I've been told that to reproduce this issue one need to use a case sensitive File System, so that the files backing up the tables `a` and `A` are not the same on disk... Does MySQL have a notion of an identifier for its table? I could easily use that to disambiguate here.
