### ISSUE TITLE
Error when trying to build using CCL

### ISSUE THREAD

**Issue by Hoya** [dimitri/pgloader#628]
```
~/pgloader-3.4.1# uname -a
Linux *.*.* 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

...

~/pgloader-3.4.1# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

...

~/pgloader-3.4.1# ccl -V
Version 1.11-r16635  (LinuxX8664)

...

~/pgloader-3.4.1# make CL=ccl DYNSIZE=256

...

[package pgloader.docs]
touch build/libs.stamp
ccl --no-init --load build/quicklisp/setup.lisp                \
             --eval '(ql:write-asdf-manifest-file "build/manifest.ql")'  \
             --eval '(quit)'
mkdir -p build/bin
ccl --no-init --load build/quicklisp/setup.lisp               \
             --eval '(ql:quickload "buildapp")'                   \
             --eval '(buildapp:build-buildapp "build/bin/buildapp.ccl")'              \
             --eval '(quit)'
To load "buildapp":
  Install 1 Quicklisp release:
    buildapp
; Fetching #<URL "http://beta.quicklisp.org/archive/buildapp/2015-12-18/buildapp-1.5.6.tgz">
; 16.00KB
==================================================
16,389 bytes in 0.00 seconds (35021.62KB/sec)
; Loading "buildapp"
[package buildapp]...........
;; loading system "buildapp"
mkdir -p build/bin
build/bin/buildapp.ccl      --logfile /tmp/build.log                \
                                                 \
                         --sbcl ccl                            \
                         --asdf-path .                           \
                         --asdf-tree build/quicklisp/local-projects     \
                         --manifest-file build/manifest.ql             \
                         --asdf-tree build/quicklisp/dists              \
                         --asdf-path .                           \
                         --load-system pgloader               \
                         --load src/hooks.lisp                   \
                         --entry pgloader:main                   \
                         --dynamic-space-size 256         \
                                             \
                         --output build/bin/pgloader.tmp
;; loading system "pgloader"
Fatal SIMPLE-ERROR:
  Compilation failed: In MAKE-KERNEL: Undeclared free variable *MONITORING-QUEUE* in /root/pgloader-3.4.1/src/utils/threads.lisp
Fatal error in "buildapp" : Error #<SILENT-EXIT-ERROR #x3020006E94BD>
Makefile:133: recipe for target 'build/bin/pgloader' failed
make: *** [build/bin/pgloader] Error 255
```

Can't seem to get around this build error.
I have no idea what the problem is

**Comment by dimitri** [comment]
Sorry about that, that's on me. Should be fixed now, please try again.

**Comment by Hoya** [comment]
Are you sure you tested your fix? I just pulled from the master branch and I'm still getting the same error


```

...

[package pgloader.docs]
touch build/libs.stamp
ccl --no-init --load build/quicklisp/setup.lisp                \
             --eval '(ql:write-asdf-manifest-file "build/manifest.ql")'  \
             --eval '(quit)'
mkdir -p build/bin
ccl --no-init --load build/quicklisp/setup.lisp               \
             --eval '(ql:quickload "buildapp")'                   \
             --eval '(buildapp:build-buildapp "build/bin/buildapp.ccl")'              \
             --eval '(quit)'
To load "buildapp":
  Install 1 Quicklisp release:
    buildapp
; Fetching #<URL "http://beta.quicklisp.org/archive/buildapp/2015-12-18/buildapp-1.5.6.tgz">
; 16.00KB
==================================================
16,389 bytes in 0.00 seconds (31382.12KB/sec)
; Loading "buildapp"
[package buildapp]...........
;; loading system "buildapp"
mkdir -p build/bin
build/bin/buildapp.ccl      --logfile /tmp/build.log                \
                                                 \
                         --sbcl ccl                            \
                         --asdf-path .                           \
                         --asdf-tree build/quicklisp/local-projects     \
                         --manifest-file build/manifest.ql             \
                         --asdf-tree build/quicklisp/dists              \
                         --asdf-path .                           \
                         --load-system pgloader               \
                         --load src/hooks.lisp                   \
                         --entry pgloader:main                   \
                         --dynamic-space-size 4096         \
                                             \
                         --output build/bin/pgloader.tmp
;; loading system "pgloader"
Fatal SIMPLE-ERROR:
  Compilation failed: In MAKE-KERNEL: Undeclared free variable *MONITORING-QUEUE* in /root/pgloader/src/utils/threads.lisp
Fatal error in "buildapp" : Error #<SILENT-EXIT-ERROR #x3020006E5C4D>
Makefile:136: recipe for target 'build/bin/pgloader' failed
make: *** [build/bin/pgloader] Error 255
```

**Comment by dimitri** [comment]
I tested here yes, and it worked well. Maybe I should try again with a make clean in between. Sorry about that, the error is strange to boot, not sure what's happening.

**Comment by dimitri** [comment]
I could reproduce the problem, and it was all about compile time dependencies in between files. In my tests here, it's now fixed. I hope it's also the case for you, please have another try!

**Comment by Hoya** [comment]
excellent, seems like the issue is resolved.

**Comment by Hoya** [comment]
One more thing, I was able to compile and get it running, but the -d option doesn't seem to do anything. I can't see any of the debug output.

**Comment by dimitri** [comment]
It seems that the CCL environment is eating the `--debug` option, I'm not sure there's anything to do to fix that. Please use `--client-min-messages debug`.
